// # internal/engine/parser/generated.go
package parser

import (
	"bytes"
	"strings"
)

// generatedMarkers lists case-insensitive substrings found in auto-generated
// file headers emitted by protoc, go generate, mockgen, stringer, swagger, etc.
var generatedMarkers = []string{
	"DO NOT EDIT",
	"Code generated by",
	"@generated",
	"/* Generated by",
	"// Generated by",
	"AUTO-GENERATED",
	"This file is automatically generated",
}

// maxHeaderBytes is how many bytes of the file we inspect for generation markers.
// Scanning only the first 8 KB is sufficient for all known generators and avoids
// reading large binary blobs through string functions.
const maxHeaderBytes = 8 * 1024

// ignoreLineMarker is the inline comment that suppresses circular analysis for
// an entire file when it appears anywhere in the source (not just the header).
const ignoreLineMarker = "// circular:ignore"

// IsGeneratedFile reports whether content appears to be an auto-generated file
// that should be excluded from circular import and secret analysis.
//
// The check is intentionally fast and conservative:
//   - Only the first maxHeaderBytes bytes are inspected for generated-file markers.
//   - A full-file scan for the inline ignore marker is always performed, but only
//     on the first maxHeaderBytes to keep it bounded.
func IsGeneratedFile(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	header := content
	if len(header) > maxHeaderBytes {
		header = header[:maxHeaderBytes]
	}
	upper := strings.ToUpper(string(header))
	for _, marker := range generatedMarkers {
		if strings.Contains(upper, strings.ToUpper(marker)) {
			return true
		}
	}
	// Check for inline ignore marker.
	return bytes.Contains(header, []byte(ignoreLineMarker))
}
