// # internal/engine/parser/generated_test.go
package parser

import (
	"testing"
)

func TestIsGeneratedFile(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "empty file",
			content: "",
			want:    false,
		},
		{
			name:    "normal go file",
			content: "package main\n\nfunc main() {}\n",
			want:    false,
		},
		{
			name:    "protobuf generated - DO NOT EDIT uppercase",
			content: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			want:    true,
		},
		{
			name:    "go generate comment",
			content: "// Code generated by stringer -type=Foo. DO NOT EDIT.\n\npackage main\n",
			want:    true,
		},
		{
			name:    "swagger generated",
			content: "// This file is automatically generated by swagger\npackage api\n",
			want:    true,
		},
		{
			name:    "@generated Facebook style",
			content: "// @generated\npackage fb\n",
			want:    true,
		},
		{
			name:    "/* Generated by block comment",
			content: "/* Generated by some tool */\npackage x\n",
			want:    true,
		},
		{
			name:    "// Generated by line comment",
			content: "// Generated by some-tool\npackage x\n",
			want:    true,
		},
		{
			name:    "AUTO-GENERATED header",
			content: "// AUTO-GENERATED CODE DO NOT MODIFY\npackage x\n",
			want:    true,
		},
		{
			name:    "inline circular:ignore",
			content: "package x\n\n// circular:ignore\nfunc Foo() {}\n",
			want:    true,
		},
		{
			name:    "marker in middle of large file is still detected within first 8KB",
			content: "package x\n// circular:ignore\n" + string(make([]byte, 100)) + "\nfunc Foo() {}\n",
			want:    true,
		},
		{
			name:    "case insensitive detection",
			content: "// code generated by mockgen\npackage mock\n",
			want:    true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := IsGeneratedFile([]byte(tc.content))
			if got != tc.want {
				t.Errorf("IsGeneratedFile() = %v, want %v, content: %q", got, tc.want, tc.content[:min(len(tc.content), 80)])
			}
		})
	}
}

func TestIsGeneratedFile_LargeFile_MarkerBeyond8KB(t *testing.T) {
	// A generated marker that appears after the first 8 KB should NOT trigger detection.
	// This is by design: large files are only scanned at the header.
	header := string(make([]byte, maxHeaderBytes+100)) // 8296 bytes of NUL
	content := header + "// Code generated by protoc\npackage x\n"
	if IsGeneratedFile([]byte(content)) {
		t.Error("marker beyond 8 KB should not be detected")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
